outpost-os/sentry-kernel

README.md
Project is registered in REUSE db.
see: https://api.reuse.software/info/github.com/outpost-os/sentry-kernel
=> Add reuse badge

.github/workflows/gnulinux.yml, .github/workflows/proof.yml, autotest/src/tests/test_shm.c, doc/concepts/uapi/syscalls.rst, doc/concepts/uapi/syscalls/meson.build, doc/concepts/uapi/syscalls/shm_get_infos.rst, kernel/include/sentry/managers/memory.h, kernel/include/sentry/syscalls.h, kernel/src/arch/asm-generic/handler-svc-lut.c, kernel/src/managers/memory/memory_shm.c, kernel/src/syscalls/meson.build, kernel/src/syscalls/sysgate_shm_get_infos.c, uapi/include/uapi/types.h, uapi/include/uapi/uapi.h, uapi/uapi/syscall.rs, uapi/uapi/systypes.rs
When sharing a shared memory with another, it would be highly easier to be able to get back the SHM infos withtout requiring DTS forge with ninja.
The global problematic is defined in #39, which is fixed by this PR.
This PR also fixes an invalid glue addition of DMA-related entries at UAPI level versus gate LUT, which were not synchronize in term of syscall identifiers, making autotest failing for the new SHM syscall.
Note: all new syscalls are append to avoid any ABI violation.
Closes #39
=> SHM: adding sys_shm_get_infos() syscall

meson.build
the firmware.hex includes:
- sentry kernel bin
- idle bin
- autotest bin
So that it can be directly flashed on the corresponding HW target for auto testing (CD usage)
=> artifact: in autotest mode, add firmware.hex to install target

kernel/src/managers/device/device.c, kernel/src/managers/memory/memory_shm-dt.c.in, kernel/src/managers/memory/memory_shm.c
fixes type-limit warning when no SHM or no device is declared in dts, avoiding empty loop statements.
closes #61
=> mroper: fix Wlimit warning when no shm or device declared

tools/parseelf.py
Fix: bad address update of .text section with .ARM
Update: support for dumping to stdout for easy dev-time infos, kept retrocompat with previous usage
store virtual and logical addresses in hex instead of int
=> tools: fix parseelf and add dump to stdout support

support/meson/version.sh
If there is no tags (which happens with personal fork for instance), `version.sh` will fail.
This PR allows to forge a simple version string in case there is no tags (yet) corresponding to short commit ID.
=> support/meson/version: fix case where there is no tags

.github/workflows/sdist.yml
`jf rt u` requires to define the target repository as `repo_name/repo_path` (see jf manual)
=> ci: fixing jf upload path

autotest/src/tests/test_dma.c, kernel/include/bsp/drivers/dma/gpdma.h, kernel/include/sentry/managers/dma.h, kernel/include/sentry/managers/task.h, kernel/src/drivers/usart/stm32-lpuart.c, kernel/src/managers/dma/dma.c, kernel/src/managers/dma/dma.h, kernel/src/managers/interrupt/interrupt.c, kernel/src/managers/task/task_core.c, kernel/src/managers/task/task_core.h, kernel/src/syscalls/sysgate_waitforevent.c, uapi/include/uapi/types.h, uapi/uapi/systypes.rs
As defined in DMA wiki, adding a new event queue specific to DMA streams vents.
As DMA streams events are specific, consolidated, events types, they should be pushed up to userspace tasks as such, instead of pushing bare IRQn.
Bare IRQn are useless to userspace, as DMA IRQ acknowledge is under the kernel control. Instead pushing consolidated event is useful for user task, as they can directly manipulate such event for functional implementation.
A DMA event is then received as a specific event of the `wait_for_event()` syscall. In that case, the event received looks like the following tuple:
```
typedef enum dma_chan_state {
GPDMA_STATE_IDLE                    = 1, /**< DMA channel idle (not set or unused) */
GPDMA_STATE_RUNNING                 = 2, /**< DMA channel is running */ …
```
=> dma: building exchange api

kernel/src/syscalls/sysgate_waitforevent.c
The way the wait_for_event() gate behaves is invalid, as it returns a STATUS_INTR when the syscall returns before its timeout definition when finding an input event.
The semantic of STATUS_INTR is not made for such a behavior, as it is made to requires from the caller to reexecute the syscall immediatly due to a interrupted function call (typically when a signal generated an interruption).
In our API, returning previously **because** there is input data should return a STATUS_OK instead.
=> fix: fixing EINTR usage for early termination of waitforevent()

.github/release.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
* Adding abstract definition of Sentry and link the doc in the README file
* Adding a CONTIBUTIONS guideline file
* Adding a CODE_OF_CONDUCT file based on the codecovenant standard file
=> doc: update README, adding contribution and conduct standard files

doc/concepts/proof/wp.rst
Misdescription of the EVA impact in documentation. thanks to Arnaud Ebalard for review.
=> framac: fixing incorrect EVA explanation in doc

dts/examples/nucleo_u5a5_autotest.dts, dts/examples/stm32f429i_disc1_autotest.dts, dts/sentry.dtsi, meson.build
Adding gcc high level security flags that increase various types of attacks such as control flow checks and redundancy, return code increased validation, etc.
Note: this PR increase the kernel footprint (approx ~9kB at the time of this PR), and thus may need to be Kconfig based. This will be made in a separated PR that cleanup the hardening part of the kernel in a dedicated Kconfig section.
=> security: adding high level security flags

kernel/Kconfig, kernel/src/managers/Kconfig, kernel/src/managers/security/entropy.c, meson.build
Make hardening flags and global sentry security selectable by kconfig.
Previously declared hardening flag inclusion are not (de)activable if needed, for example in debug or when target system flash is too small for such a size impact.
=> kconfig: Using Kconfig as global hardening selector

kernel/include/sentry/arch/asm-cortex-m/mpu_pmsa_v7.h, kernel/include/sentry/arch/asm-cortex-m/mpu_pmsa_v8.h, kernel/src/managers/memory/memory_mpu.c
This bug is not triggered in pmsav8 but is in pmsav7.
The in-RBAR register RNR value is used in pmsav7 fastload mechanism in order to specify the region that need to be updated. In pmsav8, this is not used as RNR register is used alongside multi-word writting by the CMSIS ARM implementation.
As a consequence, this bug had no impact on pmsav8 (armv8-m) but is striggered as soon as a task maps something in pmsav7 (the first resource mapped, whatever is it, being mapped at RNR 5, requiring a double ordered memcpy to the MPU.
This bug was not triggered in v7 while only mapping 4 first regions.
The fix is not the best one, and #95 has been opened for a better integrated fix.
=> mpu: fixing invalid RNR value calculation

uapi/uapi/uapi.rs
This is moved to shield rust crate as this is not part of uapi but higher level runtime feature.
=> uapi: remove println macro from uapi

support/arch/asm-cortex-m/meson.build
export `-Clinker=<same linker as sentry>`  in rustargs
=> rust: add linker to rustargs

uapi/meson.build, uapi/src/arch/x86_64.rs, uapi/src/ffi_c.rs, uapi/src/lib.rs, uapi/src/syscall.rs, uapi/src/systypes.rs
Note: all system types are using `repr(C)`, as the kernel is written in C.
=> uapi: add support for complete systypes and cargo ecosystem

autotest/src/drivers/timer/stm32-basic-timer.c, autotest/src/printf.c, autotest/src/tests/test_cycles.c, autotest/src/tests/test_dma.c, autotest/src/tests/test_gpio.c, autotest/src/tests/test_handle.c, autotest/src/tests/test_ipc.c, autotest/src/tests/test_irq.c, autotest/src/tests/test_map.c, autotest/src/tests/test_random.c, autotest/src/tests/test_shm.c, autotest/src/tests/test_signal.c, autotest/src/tests/test_sleep.c, idle/src/main.c, uapi/include/uapi/uapi.h, uapi/src/ffi_c.rs
Instead of using Linux-like copy_from_user/copy_to_user (which do not have the very same meaning as the current UAPI exchange model), using copy_to_kernel/copy_from_kernel API
=> uapi,ffi_c: fix copy_from/to API to more rust-homogeneous one

uapi/rustargs.in
otherwise, cargo will append a wrong target specifier to proc-macros...
=> uapi: do not include --target in rustargs

uapi/src/exchange.rs, uapi/src/systypes.rs
Note: Event reception/transmission are not syscall calls, but exchange interactions, meaning that a typical usage would
be :
```rust
let mut my_event = Event {
header = ExchangeHeader {
event = EventType::None,
length = 0,
peer = 0,
magic = 0,
},
data = &[u8; 128],
}
let _ = syscall::wait_for_event(EventType::Ipc.into() | EventType::Irq.into(), 0);
// get back event from kernel, including data if needed
copy_from_kernel(my_event)?;
match event.header.event {
EventType::Ipc => (),
EventType::Irq => (),
/// and so on
}
```
=> uapi: start support for rustic events (DMA, IPC, Signals and IRQ) manipulation

kernel/include/sentry/arch/asm-cortex-m/stm32l4-buses.h.in
Handle more complex bus architecture.
Some SOC have got more busses than available registers and reset and clocken might not be consistent.
e.g. AHB3/4 on the same xxxENR register and APB3ENR reserved for companion core.
=> kernel,driver,busses: enhanced stm32 busses detection in template

kernel/src/drivers/clk/stm32-rcc.c.in, kernel/src/drivers/clk/stm32l4-rcc.h.in, kernel/src/drivers/clk/stm32u5-rcc.c, kernel/src/drivers/clk/stm32u5-rcc.h.in
hsi48 is not driven the same way according to soc family:
- stm32u5 use RCC_RC register
- stm32l496/4a6 use RCC_CRRCR register
=> stm32, rcc: enhanced his48 handling

.github/workflows/gnulinux.yml
Now that gcc-14 is officially built and delivered for ARM cores, adding it to the CI
=> ci,toolchain: adding gcc-14, moving default to gcc-13.2
